Repository phamanhtuan-coder/IoT_HomeConnect_API_v2, pull requests merged in 2025-06, with the labels that each got.

#21 PR: Merge vào main
  src/controllers/production-batches.controller.ts
  src/controllers/production-tracking.controller.ts
  src/routes/index.ts
  src/routes/production-batches.routes.ts
  src/routes/production-tracking.routes.ts
  src/services/firmware.service.ts
  src/services/production-batches.service.ts
  src/services/production-tracking.service.ts
Labels: enhancement

#22 PR: stage logs not null when create
  src/services/planning.service.ts
Labels: help wanted

#23 PR: Merge vào main - Bổ sung schema - chưa test
  src/routes/firmware.routes.ts
  src/routes/production-tracking.routes.ts
  src/utils/schemas/firmware.schema.ts
  src/utils/schemas/production-tracking.schema.ts
Labels: documentation

#24 PR: merge fix planning update
  src/services/planning.service.ts
  src/services/production-batches.service.ts
Labels: help wanted

#25 Railway
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  prisma/schema.prisma
  src/config/app.ts
  src/config/firebase.ts
  src/config/nodemailer.ts
  src/controllers/firmware.controller.ts
  src/controllers/group.controller.ts
  src/routes/firmware.routes.ts
  src/routes/group.routes.ts
  src/routes/production-tracking.routes.ts
  src/routes/user-device.routes.ts
  src/services/firmware.service.ts
  src/services/group.service.ts
  src/services/production-tracking.service.ts
  src/utils/errors.ts
  src/utils/query.helper.ts
  src/utils/redis.ts
  src/utils/response.helper.ts
  src/utils/schemas/group.schema.ts
  src/utils/sql_query.ts
  tsconfig.json
Labels: enhancement

#26 PR: main to Railway
  src/services/planning.service.ts
  src/services/production-batches.service.ts
Labels: enhancement

#28 PR: update firmware_id handling in batch creation
  src/services/planning.service.ts
  src/types/planning.ts
Labels: help wanted

#31 PR: merge update planning and search customer api
  package-lock.json
  package.json
  src/controllers/customer-search.controller.ts
  src/controllers/planning.controller.ts
  src/middleware/auth.middleware.ts
  src/routes/customer-search.routes.ts
  src/routes/index.ts
  src/routes/planning.routes.ts
  src/services/customer-search.service.ts
  src/services/planning.service.ts
Labels: help wanted

#34 PR: Merge tickets vào main
  src/contants/error.ts
  src/contants/info.ts
  src/contants/status.ts
  src/controllers/ticket.controller.ts
  src/routes/ticket.routes.ts
  src/services/device.service.ts
  src/services/firmware.service.ts
  src/services/ownershipHistory.service.ts
  src/services/ticket.service.ts
  src/services/user-device.service.ts
  src/utils/errors.ts
  src/utils/response.helper.ts
Labels: enhancement

#40 PR: merge update planning schema and validate auth , update customer search
  src/controllers/customer-search.controller.ts
  src/routes/customer-search.routes.ts
  src/routes/planning.routes.ts
  src/services/customer-search.service.ts
  src/services/planning.service.ts
  src/utils/schemas/planning.schema.ts
Labels: help wanted

#41 Merge main vào railway (deploy prod)
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app.ts
  src/contants/error.ts
  src/contants/info.ts
  src/contants/status.ts
  src/controllers/auth.controller.ts
  src/controllers/component.controller.ts
  src/controllers/customer-search.controller.ts
  src/controllers/device-template.controller.ts
  src/controllers/firmware.controller.ts
  src/controllers/planning.controller.ts
  src/controllers/production-tracking.controller.ts
  src/controllers/ticket.controller.ts
  src/middleware/auth.middleware.ts
  src/middleware/validate.middleware.ts
  src/routes/component.routes.ts
  src/routes/customer-search.routes.ts
  src/routes/device-template.routes.ts
  src/routes/firmware-update-history.routes.ts
  src/routes/firmware.routes.ts
  src/routes/index.ts
  src/routes/planning.routes.ts
  src/routes/production-tracking.routes.ts
  src/routes/ticket.routes.ts
  src/services/auth.service.ts
  src/services/customer-search.service.ts
  src/services/device-template.service.ts
  src/services/device.service.ts
  src/services/firmware.service.ts
  src/services/ownershipHistory.service.ts
  src/services/planning.service.ts
  src/services/production-batches.service.ts
  src/services/production-tracking.service.ts
  src/services/ticket.service.ts
  src/services/user-device.service.ts
  src/types/auth.ts
  src/types/production-tracking.ts
  src/utils/errors.ts
  src/utils/response.helper.ts
  src/utils/schemas/component.schema.ts
  src/utils/schemas/device-template.schema.ts
  src/utils/schemas/firmware.schema.ts
  src/utils/schemas/planning.schema.ts
  src/utils/schemas/production-batches.schema.ts
  src/utils/schemas/production-tracking.schema.ts
  src/utils/sql_query.ts
Labels: help wanted

#43 Feature/device control
  postman_collection/device.json
  postman_collection/firmware.json
  postman_collection/full-collection.json
  postman_collection/merge-collection.ts
  postman_collection/planning.json
  postman_collection/production-batches.json
  postman_collection/production-tracking.json
  postman_collection/ticket-type.json
  postman_collection/ticket.json
  prisma/schema.prisma
  src/contants/error.ts
  src/controllers/auth.controller.ts
  src/controllers/device.controller.ts
  src/routes/auth.routes.ts
  src/routes/device.routes.ts
  src/routes/notification.routes.ts
  src/services/alert.service.ts
  src/services/auth.service.ts
  src/services/device.service.ts
  src/services/notification.service.ts
  src/sockets/device.socket.ts
  src/sockets/handlers/device.handlers.ts
  src/types/auth.ts
  src/types/device-state.ts
  src/types/socket.ts
  src/utils/errors.ts
  src/utils/schemas/device.schema.ts
Labels: enhancement

#44 Merge main to railway: deploy device controlling and new socket.io and some bug fixs
  postman_collection/device.json
  postman_collection/firmware.json
  postman_collection/full-collection.json
  postman_collection/merge-collection.ts
  postman_collection/planning.json
  postman_collection/production-batches.json
  postman_collection/production-tracking.json
  postman_collection/ticket-type.json
  postman_collection/ticket.json
  prisma/schema.prisma
  src/app.ts
  src/contants/error.ts
  src/controllers/auth.controller.ts
  src/controllers/device.controller.ts
  src/controllers/firmware.controller.ts
  src/controllers/notification.controller.ts
  src/controllers/planning.controller.ts
  src/controllers/production-tracking.controller.ts
  src/middleware/auth.middleware.ts
  src/middleware/validate.middleware.ts
  src/routes/auth.routes.ts
  src/routes/component.routes.ts
  src/routes/device.routes.ts
  src/routes/firmware.routes.ts
  src/routes/notification.routes.ts
  src/routes/planning.routes.ts
  src/routes/production-tracking.routes.ts
  src/services/alert.service.ts
  src/services/auth.service.ts
  src/services/device.service.ts
  src/services/firmware.service.ts
  src/services/notification.service.ts
  src/services/planning.service.ts
  src/services/production-batches.service.ts
  src/services/production-tracking.service.ts
  src/sockets/device.socket.ts
  src/sockets/handlers/device.handlers.ts
  src/types/auth.ts
  src/types/device-state.ts
  src/types/production-tracking.ts
  src/types/socket.ts
  src/utils/errors.ts
  src/utils/schemas/auth.schema.ts
  src/utils/schemas/component.schema.ts
  src/utils/schemas/device-template.schema.ts
  src/utils/schemas/device.schema.ts
  src/utils/schemas/firmware.schema.ts
  src/utils/schemas/planning.schema.ts
  src/utils/schemas/production-batches.schema.ts
  src/utils/schemas/production-tracking.schema.ts
  src/utils/sql_query.ts
Labels: help wanted

#47 Merge railway vào main
  src/app.ts
  src/controllers/auth.controller.ts
  src/routes/group.routes.ts
  src/routes/notification.routes.ts
  src/services/auth.service.ts
  src/utils/schemas/auth.schema.ts
  src/utils/schemas/device.schema.ts
  src/utils/schemas/space.schema.ts
Labels: enhancement

#49 PR: Merge ticket in main
  src/controllers/ticket.controller.ts
  src/routes/index.ts
  src/routes/ticket.routes.ts
  src/services/ticket.service.ts
  src/utils/schemas/ticket.schema.ts
  src/utils/sql_query.ts
Labels: help wanted

#54 PR main to railway
  src/controllers/customer-search.controller.ts
  src/controllers/ticket.controller.ts
  src/routes/customer-search.routes.ts
  src/routes/ticket.routes.ts
  src/services/customer-search.service.ts
  src/services/ticket.service.ts
  src/utils/schemas/ticket.schema.ts
Labels: help wanted

#58 PR merge main to Railway
  src/services/device.service.ts
  src/services/ticket.service.ts
  src/types/device.ts
Labels: bug, help wanted

#59 PR: Merge to main
  src/contants/info.ts
  src/controllers/auth.controller.ts
  src/controllers/sharedPermission.controller.ts
  src/routes/sharedPermission.routes.ts
  src/services/auth.service.ts
  src/services/production-tracking.service.ts
  src/services/sharedPermission.service.ts
  src/services/ticket.service.ts
  src/types/auth.ts
  src/types/production-tracking.ts
  src/utils/schemas/production-tracking.schema.ts
Labels: enhancement
